name = "torchstudy"
pages_build_output_dir = "."
compatibility_date = "2026-02-22"

[[d1_databases]]
binding = "DB"
database_name = "torchstudy-db"
database_id = "173b003c-f902-41d1-ada9-54824be6b2de"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "torchstudy-media"
